# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ShoutAboutApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'JSQMessagesViewController'

  # Pods for ShoutAboutApp

    pod 'CocoaLumberjack'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'Google/SignIn'
    pod 'xmpp-messenger-ios'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Digits'
    pod 'TwitterCore'
    pod 'JSQMessagesViewController'
    pod 'XMPPFramework'
    #pod 'XMPPFramework', :podspec => 'https://raw.githubusercontent.com/andrey-justo-movile/XMPPFramework/3.7.2/XMPPFramework.podspec.json'
    # pod 'ReactiveCocoa', '4.0.0-alpha-3'
    pod 'Reachability'
    #pod 'ChameleonFramework/Swift', "2.0.1"
    #pod 'ChameleonFramework/Swift'
    #pod 'SnapKit', '~>0.22.0'
    pod 'SnapKit'
    pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git'
    pod 'OpenUDID'
    #pod 'SwiftyJSON',   '~>2.3.2'
    pod 'SwiftyJSON'
    pod 'SDWebImage' 
    pod 'DeepLinkKit'
    pod 'NYTPhotoViewer'
    pod 'PhoneNumberKit'
    #pod 'PhoneNumberKit', '~> 0.8'
    #pod 'Toucan', '~> 0.5.0'
   pod 'Toucan'
    pod "youtube-ios-player-helper"
    pod "Watchdog"
    pod 'SwiftDate'
    pod 'Toucan'
    #pod 'CocoaLumberjack', '~> 2.4.0'
    


end

