# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShoutAboutApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'JSQMessagesViewController'

  # Pods for ShoutAboutApp


    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Digits'
    pod 'TwitterCore'
    pod 'JSQMessagesViewController'
    pod 'XMPPFramework'
    #pod 'XMPPFramework', :podspec => 'https://raw.githubusercontent.com/andrey-justo-movile/XMPPFramework/3.7.2/XMPPFramework.podspec.json'
    pod 'ReactiveCocoa', '4.0.0-alpha-3'
    pod 'Reachability'
    pod 'ChameleonFramework/Swift', "2.0.1"
    pod 'SnapKit', '~>0.22.0'
    pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git'
    pod 'OpenUDID'
    pod 'SwiftyJSON',   '~>2.3.2'
    pod 'SDWebImage' ,   '3.8.0'
    pod 'DeepLinkKit'
    pod 'NYTPhotoViewer'
    #pod 'PhoneNumberKit'
    pod 'PhoneNumberKit', '~> 0.8'
    pod 'Toucan', '~> 0.5.0'
    pod "youtube-ios-player-helper", "0.1.4"
    pod "Watchdog", "2.1"
    pod 'SwiftDate', '~>3.0.8'
    pod 'CocoaLumberjack', '~> 2.4.0'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'Google/SignIn'
    pod 'xmpp-messenger-ios'


end

# Strip alpha/beta notations from build numbers
post_install do |installer|
    plist_buddy = "/usr/libexec/PlistBuddy"
    
    installer.pods_project.targets.each do |target|
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip
        
        stripped_version = /^([\d\.]*)/.match(version).captures[0]
        
        version_parts = stripped_version.split('.').map { |s| s.to_i }
        
        # ignore properly formatted versions
        unless version_parts.slice(0..2).join('.') == version
            
            major, minor, patch = version_parts
            
            minor ||= 0
            patch = 999
            
            fixed_version = "#{major}.#{minor}.#{patch}"
            
            puts "Changing version of #{target} from #{version} to #{fixed_version} to make it pass iTC verification."
            
            `#{plist_buddy} -c "Set CFBundleShortVersionString #{fixed_version}" "#{plist}"`
        end
    end
end
